import { BlacklightEvent } from '../types';
import { Browser } from 'puppeteer';
export declare const safePath: (baseDir: string, ...segments: string[]) => string;
export declare const hasOwnProperty: (object: object, property: string) => any;
export declare const closeBrowser: (browser: Browser) => Promise<void>;
export declare const clearDir: (outDir: string, mkNewDir?: boolean) => void;
export declare const loadJSONSafely: (str: string) => any;
export declare const groupBy: (key: any) => (array: any) => any;
export declare const serializeCanvasCallMap: (inputMap: any) => {};
export declare const getScriptUrl: (item: BlacklightEvent) => any;
export declare const loadEventData: (dir: string, filename?: string) => any[];
export declare const getHashedValues: (algorithm: any, object: any) => {};
